### ISSUE TITLE
how to use  google account sign in 

### ISSUE THREAD

**Issue by wadelee1986** [jkomoros/boardgame#500]
I got  the following err  when i selected  google account, 

The given sign-in provider is disabled for this Firebase project. Enable it in the Firebase console, under the sign-in method tab of the Auth section.

Who can help me ?

**Comment by jkomoros** [comment]
Ah, I think I had misconfigured the example-boardgame firebase project. I just enabled Google signin. Does it work now?

**Comment by jkomoros** [comment]
Assuming that this is now fixed
